apiVersion: v1
kind: Service
metadata:
  name: q2aminapp
  labels:
    app: q2aminapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30036
    targetPort: 80
    protocol: TCP
  selector:
    app: q2aminapp
